### ISSUE TITLE
Could the bot fire the daily message a bit earlier?

### ISSUE THREAD

**Issue by AimPizza** [TheItsNameless/cs24-1-bot#9]
Is there a specific reason for the bot firing at 7am or was that more or less guessed?
In my case, 7am isn't ideal since I have to get going by then. It would be really nice if we could set the bot to fire at 5 or 6am so one could decide in the morning on how much lunch to pack.

**Comment by TheItsNameless** [comment]
There is no specific reason, i just thought that would be a good time. I will change it to 6am, as i think 5am might be a bit too early.
